### ISSUE TITLE
dd function not working

### ISSUE THREAD

**Issue by watarutmnh** [studioespresso/craft3-dumper#10]
Hello
dd() doesn't working and it outputs a blank page.
dump() and d() seems to have no problem and works as good.
Here is my app info:
PHP version 7.2.1
MySQL 5.6.38
Craft Pro 3.1.29
Dumper 1.3.1

**Comment by watarutmnh** [comment]
My craft environment is "dev", so it should have error info but I get only a blank page.

**Comment by janhenckens** [comment]
Hey! Where on your code are you using the function? In twig template, in a controller,... ?

**Comment by janhenckens** [comment]
Can confirm that this broke in Craft 3.1.29, still works on 3.1.28.
Related to Craft requiring Twig 2.11 in the latest update.

**Comment by watarutmnh** [comment]
Hi, The issue is In twig template.

**Comment by janhenckens** [comment]
Should be fixed with upgrading to version 2.0.0 of the plugin. Do get in touch if you run into any other issues.

Thanks
Jan
