### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by toddprouty** [studioespresso/craft3-dumper#12]
Do you plan to upgrade/fork this plugin to support Craft 4?

**Comment by janhenckens** [comment]
Hey @toddprouty! I have a branch ready but don't think I tagged anything yet. Will try to get to get to that this evening.

Still having an issue with getting dd() to work though, but what I have now should be enough to not block you when upgrading.

**Comment by janhenckens** [comment]
Tagged a beta release that works with Craft 4, can you give that a try?

**Comment by rostockahoi** [comment]
Works for me.

Install with `composer require studioespresso/craft-dumper:3.0.0-beta.1 && php craft plugin/install dumper`
