### ISSUE TITLE
Issue with requirements / minimum stability - breaks Craft 3.0.0-RC2 install

### ISSUE THREAD

**Issue by juresrpcic** [studioespresso/craft3-dumper#3]
Composer reports this error when trying to update to RC2:

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - studioespresso/craft-dumper 1.1.1 requires craftcms/cms 3.0.0-RC1 -> satisfiable by craftcms/cms[3.0.0-RC1] but these conflict with your requirements or minimum-stability.
    - studioespresso/craft-dumper 1.1.0 requires craftcms/cms dev-release/3.0.0-RC1 -> no matching package found.
    - studioespresso/craft-dumper 1.1.1 requires craftcms/cms 3.0.0-RC1 -> satisfiable by craftcms/cms[3.0.0-RC1] but these conflict with your requirements or minimum-stability.
    - Installation request for studioespresso/craft-dumper ^1.1 -> satisfiable by studioespresso/craft-dumper[1.1.0, 1.1.1].
```

Might be locked to `3.0.0-RC1` instead of `^3.0.0-RC1`.

**Comment by janhenckens** [comment]
That should be fixed by now, can you try again?

**Comment by juresrpcic** [comment]
@janhenckens The merged pull request would solve the issue, but I'm not getting the latest version - https://semver.mwl.be/ shows the latest version as `1.1.1`.

**Comment by brandonkelly** [comment]
composer.json still has its `version` property set to 1.1.1: https://github.com/studioespresso/craft3-dumper/blob/34ebb667089ab774976246054f81361f3fcc80b4/composer.json#L5

For Packagist and the Plugin Store to pick up the new version, its tag name and `version` property need to match up. (Or you can just remove the `version` property from composer.json and not have to worry about keeping it updated.)

**Comment by janhenckens** [comment]
That's what happens when you quickly release something between 9 other things :)
Fixed now!
