### ISSUE TITLE
Exception in console caused by craft3-dumper

### ISSUE THREAD

**Issue by FreekVR** [studioespresso/craft3-dumper#4]
Getting an error in the craft3 console with this plugin enabled due to a missing implementation of the Plugin::init() function.

root@ce9b9b184deb:/var/www/html# ./craft help
Exception 'yii\base\InvalidParamException' with message 'Invalid path alias: @'

in /var/www/html/pcf/vendor/yiisoft/yii2/BaseYii.php:154

Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/base/Module.php(257): yii\BaseYii::getAlias('@')
#1 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(250): yii\base\Module->getControllerPath()
#2 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(245): yii\console\controllers\HelpController->getModuleCommands(Object(studioespresso\craftdumper\CraftDumper))
#3 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(179): yii\console\controllers\HelpController->getModuleCommands(Object(craft\console\Application))
#4 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(191): yii\console\controllers\HelpController->getCommands()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(286): yii\console\controllers\HelpController->getCommandDescriptions()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#7 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)

**Comment by janhenckens** [comment]
Thanks for the PR to fix this Freek! The fix is out in version 1.1.3 https://github.com/studioespresso/craft3-dumper/releases/tag/1.1.3
