### ISSUE TITLE
z-index issue

### ISSUE THREAD

**Issue by lukeyouell** [studioespresso/craft3-dumper#7]
I spotted a z-index issue with CP modals (screenshot attached)

<img width="921" alt="image" src="https://user-images.githubusercontent.com/24975058/39871346-62de3ff8-545c-11e8-82f2-3fb4ff762716.png">

**Comment by janhenckens** [comment]
Thanks for catching that! I assume you're not dumping in the modal but in the entry page behind it?

**Comment by janhenckens** [comment]
Fixed in 1.2.1 :)
